### PR TITLE
(MODULES-10814) - Replace `IO.popen` with `Puppet:Util:Execution.execute`

### PR DESCRIPTION
**Pull request by david22swan**
This is a hardening change meant to help prevent issues from occurring.

### CODE REVIEW

**Comment by david22swan** [comment]
Puppet 5:
Successful on 19 nodes: ["pure-traitor.delivery.puppetlabs.net, oracle-7-x86_64", "cheerful-visa.delivery.puppetlabs.net, ubuntu-1404-x86_64", "rank-sanatorium.delivery.puppetlabs.net, scientific-7-x86_64", "rugged-crucible.delivery.puppetlabs.net, centos-6-x86_64", "likely-yield.delivery.puppetlabs.net, scientific-6-x86_64", "stout-endowment.delivery.puppetlabs.net, redhat-6-x86_64", "choral-quatrain.delivery.puppetlabs.net, centos-7-x86_64", "rousseauan-pimp.delivery.puppetlabs.net, oracle-6-x86_64", "prefab-chewing.delivery.puppetlabs.net, centos-5-x86_64", "benign-terrain.delivery.puppetlabs.net, oracle-5-x86_64", "flexible-basin.delivery.puppetlabs.net, debian-10-x86_64", "odd-midwife.delivery.puppetlabs.net, debian-9-x86_64", "blond-downturn.delivery.puppetlabs.net, redhat-7-x86_64", "unformed-dryer.delivery.puppetlabs.net, ubuntu-1604-x86_64", "limpid-closet.delivery.puppetlabs.net, redhat-5-x86_64", "anomic-buckle.delivery.puppetlabs.net, debian-8-x86_64", "gummy-dashboard.delivery.puppetlabs.net, redhat-8-x86_64", "double-alto.delivery.puppetlabs.net, centos-8-x86_64", "diachronic-gray.delivery.puppetlabs.net, ubuntu-1804-x86_64"]

**Comment by david22swan** [comment]
Puppet 6:
Successful on 20 nodes: ["aloof-leafmold.delivery.puppetlabs.net, oracle-7-x86_64", "smug-footbridge.delivery.puppetlabs.net, ubuntu-1404-x86_64", "wise-exultation.delivery.puppetlabs.net, centos-6-x86_64", "mauve-dogmatism.delivery.puppetlabs.net, centos-7-x86_64", "bold-competence.delivery.puppetlabs.net, redhat-6-x86_64", "nonmagical-nut.delivery.puppetlabs.net, scientific-6-x86_64", "barren-chunk.delivery.puppetlabs.net, ubuntu-1604-x86_64", "wiry-fertilizer.delivery.puppetlabs.net, debian-10-x86_64", "brutal-battle.delivery.puppetlabs.net, redhat-7-x86_64", "mobile-hall.delivery.puppetlabs.net, centos-8-x86_64", "vague-semblance.delivery.puppetlabs.net, debian-9-x86_64", "risky-grappling.delivery.puppetlabs.net, oracle-6-x86_64", "oviform-epitaph.delivery.puppetlabs.net, scientific-7-x86_64", "tool-thumbnail.delivery.puppetlabs.net, redhat-5-x86_64", "grubby-marathon.delivery.puppetlabs.net, debian-8-x86_64", "mock-courtroom.delivery.puppetlabs.net, redhat-8-x86_64", "pyhrric-foaming.delivery.puppetlabs.net, ubuntu-2004-x86_64", "inside-priority.delivery.puppetlabs.net, centos-5-x86_64", "lacy-butterfly.delivery.puppetlabs.net, oracle-5-x86_64", "boxy-stretch.delivery.puppetlabs.net, ubuntu-1804-x86_64"]

**Comment by david22swan** [comment]
Change made to remove commented out line.

**Comment by david22swan** [comment]
Setting rvm for test's to 2.5.8 in order to prevent the bolt provisioning issue from arising again. The use of Tempfile while on rvm 2.5.7 seems to set bolt to the broken 2.4.1 version.

**Review by sanfrancrisko — APPROVED** [review]

**Pull request merged**
